sources:
  - name: Tenderize
    handler:
      graphql:
        endpoint: '{context.subgraph:https://api.studio.thegraph.com/query/45970/v2-testnet/version/latest}'
documents:
  - ./gql/**/*.gql

additionalTypeDefs: |
  extend type Query {
    getUserMultichain(user: ID!, subgraphs: [String!]!): User!
  }

additionalResolvers:
  - ./src/resolvers.ts

codegen:
  contextType: 'MeshContext & { subgraph: string }'